name: ont_taxonomy_r
channels:
  - conda-forge
  - bioconda
  - default
  - r
dependencies:
  - conda-forge::r-base=4.2.1
  - conda-forge::r-tidyverse=1.3.2
  - conda-forge::r-data.table=1.14.4
  - conda-forge::r-glue=1.6.2
  - conda-forge::r-openxlsx=4.2.5.1
  - conda-forge::r-jsonlite=1.8.3

